Name: Go build and test

On: [push]

 jobs:
  go test:
  runs on: Ubuntu latest
  Steps:
    - uses: actions/checkout@v3

    - name: Set up Go 
      uses: actions/setup-go@v3
  with:
         go-version: 1.15
    - name: Build
       run:  go build -v ./...

    - name: Test
       run:  go test -v ./..../

    - name: install
       run: go install

    - name: open file
       run:  |
             cd $GOPATH/bin/
             ls $GOPATH/bin/
             ./main
         
